config/routes.rb
Rails.application.routes.draw do
  get 'general_info/:id/profile', to: 'general_info#profile', as: 'profile'
  # to retrive states and cities
  get 'messages', to: 'room#index'
  get 'states/:country_id', to: 'states#index', as: 'states'
  get 'cities/:state_id', to: 'cities#index', as: 'cities'
  post 'general_info/generate_about_me', to: 'general_info#generate_about_me', as: :generate_about_me

  post '/dm/:id', to: 'room#create_message'

  get '/dm', to: 'room#show'

  get '/dm/:id', to: 'room#show'

  get 'galleries/new' => 'galleries#new', :as => 'galleries/newg'

  get 'galleries/private_info/:id' => 'galleries#private_info'

  #get 'galleries/create'

  get 'galleries/destroy/:id'=> 'galleries#destroy', :as => 'galleries_destroy'

  get 'show_profile/destroy/:id'=> 'show_profile#destroy', :as => 'show_profile_destroy'

  get 'galleries/delete/:id'=> 'galleries#delete', :as => 'galleries_delete'

  get 'galleries/index'

  get 'galleries/show' => 'galleries#show', :as => 'galleries/show'

  post 'galleries/update' => 'galleries#update', :as => 'galleries/update'

  post 'galleries/create' => 'galleries#create', :as => 'galleries/create'

  # NXTFolio : Added in Spring 2023 for tagging feature
  post '/galleries/:id/create_tagging', to: 'galleries#create_tagging', as: 'create_tagging_gallery'
  delete '/galleries/:id/destroy_tagging', to: 'galleries#destroy_tagging', as: 'destroy_tagging_gallery'

  # spring2023 add/delete images in gallery
  get '/galleries/:id/edit', to: 'galleries#edit', as: 'edit_gallery'
  get '/galleries/:id/show', to: 'galleries#show', as: 'gallery'

  put '/galleries/:id/show', to: 'galleries#update', as: 'gallery/update'


  get '/galleries/:id/delete/:idx', to: 'galleries#delete', as: 'gallery_delete'

  get '/galleries/:id/add_images', to: 'galleries#transfer', as: 'gallery_added_image'

  # Fall 2023: To add comments
  get '/galleries/:id/comments', to: 'galleries#add_comment', as: 'gallery_add_comment'
  post '/galleries/:id/comments', to: 'galleries#post_comment', as: 'gallery_post_comment'

  # Winter 2024: To add tags
  get '/galleries/:id/tags', to: 'galleries#add_tag', as: 'gallery_add_tag'
  post '/galleries/:id/tags', to: 'galleries#create_tag', as: 'gallery_create_tag'

  #get 'template/create'
  #post 'template/create' => 'template#create', :as => 'template/create1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                   registrations: "users/registrations",
                                   sessions: "devise/sessions" }, 
                    skip: [:registrations] 
  get 'general_info_list' => 'general_info#list', :as => 'general_info_list'
  get 'general_info_save' => 'general_info#save', :as => 'general_info_save'
  get 'general_info/edit' => 'general_info#edit', :as => 'general_info/edit'
  get 'general_info/edit2' => 'general_info#edit2', :as => 'general_info/edit2'
  get 'general_info/edit_travel' => 'general_info#edit_travel', :as => 'general_info/edit_travel'
  get 'general_info/new', to: 'general_info#new', as: 'general_info_new'
  get 'general_info/new2' => 'general_info#new2', :as => 'general_info/new2'
  post 'general_info/update' => 'general_info#update', :as => 'general_info/update'
  get 'general_info/edit_profession' => 'general_info#edit_profession', :as => 'general_info/edit_profession'
  post 'general_info/update_profession' => 'general_info#update_profession', :as => 'general_info/update_profession'
  get 'general_info/profession_specific' => 'general_info#profession_specific', :as => 'general_info/profession_specific'
  post 'general_info/profession_specific' => 'general_info#profession_specific_create', :as => 'general_info/profession_specific_create'
  # Follow Feature
  get 'general_info/follow/:id' => 'general_info#follow'
  get 'general_info/unfollow/:id' => 'general_info#unfollow'

  namespace :admin do
    get '/' => 'admin#landing'
    get '/create' => 'admin#create'
    post '/create' => 'admin#create'
    get '/edit' => 'admin#edit'
    post '/edit' => 'admin#edit'  
    get '/delete' => 'admin#delete'
    post '/delete' => 'admin#delete'
  end

  namespace :api do
    get 'users', to: 'general_info#index'
    get 'delete/:id', to: 'general_info#delete'
    get 'toggle_access/:id', to: 'general_info#toggle_access'
    # resources :general_info, only: [:index]
  end

  get '/general_info/make_admin/:user' => 'general_info#make_admin'

  get 'edit_job' => 'edit_job#edit'
  post 'edit_job' => 'edit_job#update'
  patch 'edit_job/update' => 'edit_job#update'
  post 'edit_job/update' => 'edit_job#update'
  get 'login_info_list' => 'login_info#list', :as => 'login_info_list'
  get 'login_info/login' => 'login_info#login', :as => 'login_info/login'
  post 'login_info/login_submit' => 'login_info#login_submit', :as => 'login_info/login_submit'
  get 'login_info/logout' => 'login_info#logout', :as => 'login_info/logout'
  post 'login_info/new' => 'login_info#new', :as => 'login_info/new'
  post 'login_info/create' => 'login_info#create', :as => 'login_info/create'
  get 'login_info/edit' => 'login_info#edit', :as => 'login_info/edit'
  post 'login_info/update' => 'login_info#update', :as => 'login_info/update'
  get 'unconfirmed_user/new' => 'unconfirmed_user#new', :as => 'unconfirmed_user/new'
  post 'unconfirmed_user/verify' => 'unconfirmed_user#verify', :as => 'unconfirmed_user/verify'
  get 'unconfirmed_user/regenerate_token' => 'unconfirmed_user#regenerate_token', :as => 'unconfirmed_user/regenerate_token'


  get 'login' => 'login_info#login', :as => 'login'
  get  'logout' => 'login_info#logout', :as => 'logout'
  # post 'create' => 'login_info#create', :as => 'create'


  get 'specific_designer_list' => 'specific_designer#list', :as => 'specific_designer_list'
  get 'specific_designer/edit' => 'specific_designer#edit', :as => 'specific_designer/edit'
  post 'specific_designer/update' => 'specific_designer#update', :as => 'specific_designer/update'
  delete 'specific_designer/destroy' => 'specific_designer#destroy', :as => 'specific_designer/destroy'

  get 'specific_model_list' => 'specific_model#list', :as => 'specific_model_list'
  get 'specific_model/edit' => 'specific_model#edit', :as => 'specific_model/edit'
  post 'specific_model/update' => 'specific_model#update', :as => 'specific_model/update'
  delete 'specific_model/destroy' => 'specific_model#destroy', :as => 'specific_model/destroy'

  get 'specific_photographer_list' => 'specific_photographer#list', :as => 'specific_photographer_list'
  get 'specific_photographer/edit' => 'specific_photographer#edit', :as => 'specific_photographer/edit'
  post 'specific_photographer/update' => 'specific_photographer#update', :as => 'specific_photographer/update'
  delete 'specific_photographer/destroy' => 'specific_photographer#destroy', :as => 'specific_photographer/destroy'

  get 'show_profile/mymodel' => 'show_profile#show_model', :as => 'show_profile_show_model'
  get 'show_profile' => 'show_profile#show_profile', :as => 'show_profile_show_profile'

  get 'search_profile/show' => 'search_profile#show', :as => 'search_profile/show'
  get 'search_profile/search' => 'search_profile#search', :as => 'search_profile/search'
  get 'search_profile/search_general' => 'search_profile#search_general', :as => 'search_profile/search_general'
  get 'search_profile/search_job' => 'search_profile#search_job', :as => 'search_profile/search_job'

  get 'search_profile/search_login' => 'search_profile#search_login', :as => 'search_profile/search_login'

  get 'search_profile/search_model' => 'search_profile#search_model', :as => 'search_profile/search_model'
  get 'search_profile/search_photographer' => 'search_profile#search_photographer', :as => 'search_profile/search_photographer'
  get 'search_profile/search_specific' => 'search_profile#search_specific', :as => 'search_profile/search_specific'
  get 'search_profile/search_specific_model' => 'search_profile#search_specific_model', :as => 'search_profile/search_specific_model'
  get 'search_profile/search_specific_photographer' => 'search_profile#search_specific_photographer', :as => 'search_profile/search_specific_photographer'
  get 'search_profile/show_profile/:id' => 'search_profile#show_profile', :as => 'search_profile/show_profile'
  get 'add_profession' => 'template#index', :as => 'template'
  post '/' => 'general_info#index', :as => 'general_info_index_post'

  get 'application/index' => 'application#index', :as => 'application/index'

  get 'search_engine/show' => 'search_engine#show', :as => 'search_engine/show'
  get 'search_engine/search' => 'search_engine#search', :as => 'search_engine/search'

  get 'job_search/jobshow' => 'job_search#jobshow', :as => 'job_search/jobshow'
  #get 'job_search/jobsearch' => 'job_search#jobsearch', :as => 'job_search/jobsearch'

  # get 'job_info/post_job' => 'job_info#post_job', :as => 'job_info/post_job1'
  post '/job_info/post_job', to: 'job_info#post_job', as: 'job_info_post_job'
  get 'job_info/index',   to: 'job_info#index',  as: 'job_info/index'
  get 'job_info/search', to: 'job_info#search', as: 'job_info/search'
  get 'job_info/new_job', to: 'job_info#new_job', as: 'job_info_new_job'
  get 'job_info/show/:id', to: 'job_info#show', as: 'job_info_show'
  # delete 'job_info/:id/del(.:format)', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/del', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/visitor', to: 'job_info#visitor_show', as: 'visitor_job_info'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Defines the root path route ("/")

app/helpers/search_profile_helper.rb
module SearchProfileHelper
end

app/views/search_profile/search.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>FashioNXT</title>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="<%= asset_path "favicon.jpg"%>">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="<%= asset_path "bootstrap.min.css"%>">
		<link rel="stylesheet" href="<%= asset_path "icon.css"%>">
		<link rel="stylesheet" href="<%= asset_path "loader.css"%>">
		<link rel="stylesheet" href="<%= asset_path "idangerous.swiper.css"%>">
		<link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
		<link rel="stylesheet" href="<%= asset_path "stylesheet.css"%>">
		<link rel="stylesheet" href="<%= asset_path "notifications.css"%>">
		
	</head>
	<body data-spy="scroll" data-target="blog-detail-2.htmlscrollspy">
	

	<!-- THE LOADER -->

	<div class="be-loader">
    	<div class="spinner">
			<img id="spinner-img" src="<%= asset_path "logo.png"%>"  alt="">
			<p class="circle">
			  <span class="ouro">
			    <span class="left"><span class="anim"></span></span>
			    <span class="right"><span class="anim"></span></span>
			  </span>
			</p>
		</div>
    </div>
	<!-- THE HEADER -->
<%= render 'shared/header' %>
	
	
	<!-- MAIN CONTENT -->
	<div id="content-block">
		<div class="container be-detail-container">
			<div class="row">
				<div class="col-xs-12 col-md-3 left-feild">
					<div class="be-vidget hidden-xs hidden-sm" id="scrollspy">
						<h3 class="letf-menu-article">
							Select Search
						</h3>
						<div class="creative_filds_block">
							<ul class="ul nav">
								<li class="edit-ln"><a href="#search-by-mail">Search by Email</a></li>
								<li class="edit-ln"><a href="#advanced-search">Advanced Search</a></li>
							</ul>
						</div>	
					</div>
	
				</div>
					<div class="col-xs-12 col-md-9 _editor-content_">
					  <%= form_tag(search_profile_search_login_path, :method => 'get') do %>
						<div class="sec"  data-sec="search-by-mail">
							<div class="be-large-post">
								<div class="info-block style-2">
									<div class="be-large-post-align "><h3 class="info-block-label">Search By Email</h3></div>
								</div>
								<div class="be-large-post-align">
									<div class="row">
										<!--email-->
										<div class="input-col col-xs-12 col-sm-8 col-sm-offset-2">
											<div class="form-group fg_icon focus-2">
												<!--<div class="cols-sm-10">-->
        									<div class="input-group">
        										<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
        										<%= text_field_tag "email", nil, class: 'form-control', placeholder: "Enter email id"%>
        										<%= select_tag "email_regex", options_for_select([['Contains', 'Contains'], ['Starts With', 'Starts With'], ['Ends With', 'Ends With'], ['Exactly Matches','Exactly Matches']]), :class => 'form-control' %>
        										</p>
        									</div>
        								<!--</div>-->
											</div>
										</div>
										<div class="input-col col-xs-12 col-sm-12">
											<div class="form-group fg_icon focus-2">
												<div class="form-group ">
								          <%= button_tag 'Search' , :class => 'btn btn-block color-2 size-1 hover-3' , :name => 'Search by email' %>
        						    </div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<% end %>
						
						<%= form_tag(search_profile_search_general_path, :method => 'get') do %>
						<div class="sec"  data-sec="advanced-search">
							<div class="be-large-post">
								<div class="info-block style-2">
									<div class="be-large-post-align"><h3 class="info-block-label">Advanced Search</h3></div>
								</div>
								<div class="be-large-post-align">
									<div class="row">	
										<!--profession-->
										<div class="input-col col-xs-12 col-sm-8 col-sm-offset-2">
											<div class="form-group fg_icon focus-2">
												<!--<div class="cols-sm-10">-->
												  <div class="form-label  ">Proffesion</div>
        									<div class="input-group">
        										<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                                <%= select_tag "job_type", options_for_select(@possible_Jobs), :class => 'form-control' %>
        										</p>
        									</div>
        								<!--</div>-->
											</div>
										</div>
										<!--submit button-->
										<div class="input-col col-xs-12 col-sm-12">
											<div class="form-group fg_icon focus-2">
												<div class="form-group ">
								          <%= button_tag 'Search' , :class => 'btn btn-block color-2 size-1 hover-3' %>
        						    </div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<% end %>
					</div>
			</div>
		</div>
	</div>
	<footer>	
		<div class="footer-main">
			<div class="container-fluid custom-container">
				<div class="row">	
					<div class="col-md-3 col-xl-4">
						<div class="footer-block">
							<h1 class="footer-title">About Us</h1>
							<p>FashioNXT creates innovative fashion experiences and the creative edge in lifestyle technology.</p>
							<ul class="soc_buttons">
								<li><a href="https://www.facebook.com/FASHIONXtONLINE/"><i class="fa fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/fashionxtonline"><i class="fa fa-twitter"></i></a></li>
								<li><a href="https://www.pinterest.com/fashionxtonline/"><i class="fa fa-pinterest"></i></a></li>
								<li><a href="https://www.instagram.com/fashionxtonline/"><i class="fa fa-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/company/fashionxt/"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-6 col-xl-2">
						<div class="footer-block">
							<h1 class="footer-title">Some Links</h1>
							<div class="row footer-list-footer">
							<div class="col-md-6">
							<ul class="link-list">
                                <li><a href="https://fashionxt.com/agency/">About Us</a></li>
                                <li><a href="https://fashionxt.com/contact/">Help</a></li>
                                <li><a href="https://fashionxt.com/contact/">Contacts</a></li>
                                <li><a href="https://www.linkedin.com/company/fashionxt/jobs/">Job</a></li>
							</ul></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container-fluid custom-container">
				<div class="col-md-12 footer-end clearfix">
					<div class="left">
						<span class="copy">© 2018. All rights reserved. <span class="white"><a href="fashionxt.com"> FashioNXT</a></span></span>
						<span class="created">Created with LOVE by <span class="white"><a href=""> ThatSoftwareEngineeringGroup</a></span></span>
					</div>
				</div>			
			</div>
		</div>		
	</footer>

	<div class="be-fixed-filter"></div>
	<%= form_for :login_info, :action => 'login_submit', :url => login_info_login_submit_path do |form| %>
	<div class="large-popup login">
		<div class="container large-popup-container">
			<div class="row">
				<div class="col-md-8 col-md-push-2 col-lg-6 col-lg-push-3  large-popup-content">
					<div class="row">
						<div class="col-md-12">
							<i class="fa fa-times close-button"></i>
							<h5 class="large-popup-title">Log in</h5>
						</div>
						<form action="#" class="popup-input-search" method="post">
						<div class="col-md-6">
							<%= form.text_field :email, :class => 'input-signtype', :id => 'email', :placeholder => 'Your Email', :required => ''%>
							<!--<input class="input-signtype" type="email" required="" placeholder="Your email">-->
						</div>
						<div class="col-md-6 form-group">
							<%= form.password_field :password, :class => 'input-signtype', :id => 'password', :placeholder => 'Your Password', :required => '' %>
							<!--<input id= "password" class="input-signtype" type="password" required="" placeholder="Password">-->
						</div>
						<div class="col-xs-6"></div>
						<div class="col-xs-6 for-signin">
							<%= form.submit "SIGN IN", :class => 'be-popup-sign-button', :type => 'submit' %>
							<!--<input type="submit" class="be-popup-sign-button" value="SIGN IN">-->
						</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<!-- SCRIPT	-->
	<script src="<%= asset_path "jquery.min.js"%>"></script>
	<script src="<%= asset_path "jquery-ui.js"%>"></script>
	<script src="<%= asset_path "bootstrap.min.js"%>"></script>		
	<script src="<%= asset_path "idangerous.swiper.min.js"%>"></script>
	<script src="<%= asset_path "jquery.mixitup.js"%>"></script>
	<script src="<%= asset_path "jquery.viewportchecker.min.js"%>"></script>
	<script src="<%= asset_path "global.js"%>"></script>
	</body>
</html>
>>>>>>> saturdaynight-fever

app/views/search_profile/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>FashioNXT</title>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="<%= asset_path "favicon.jpg"%>">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="<%= asset_path "bootstrap.min.css"%>">
		<link rel="stylesheet" href="<%= asset_path "icon.css"%>">
		<link rel="stylesheet" href="<%= asset_path "loader.css"%>">
		<link rel="stylesheet" href="<%= asset_path "idangerous.swiper.css"%>">
		<link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
		<link rel="stylesheet" href="<%= asset_path "stylesheet.css"%>">
		<link rel="stylesheet" href="<%= asset_path "profile.css"%>">
		
	</head>
	<body data-spy="scroll" data-target="blog-detail-2.htmlscrollspy">
	

	<!-- THE LOADER -->

	<div class="be-loader">
    	<div class="spinner">
			<img id="spinner-img" src="<%= asset_path "logo.png"%>"  alt="">
			<p class="circle">
			  <span class="ouro">
			    <span class="left"><span class="anim"></span></span>
			    <span class="right"><span class="anim"></span></span>
			  </span>
			</p>
		</div>
    </div>
	<!-- THE HEADER -->
	<header>
		<div class="container-fluid custom-container">
			<div class="row no_row row-header">
				<div class="brand-be">
					<a href="/">
						<img class="logo-c active be_logo"  src="<%= asset_path "logo.png"%>" alt="logo">
						<img class="logo-c be_logo" src="<%= asset_path "logo.png"%>" alt="logo2">
						<img  class="logo-c be_logo" src="<%= asset_path "logo.png"%>" alt="logo3">
						<img class="logo-c be_logo" src="<%= asset_path "logo.png"%>" alt="logo4">
					</a>
				</div>
				
				<!--navbar options-->
				
				<div class="header-menu-block">
					<button class="cmn-toggle-switch cmn-toggle-switch__htx"><span></span></button>
					<ul class="header-menu" id="one">
						<!--<li><a href="activity.html">Activity</a></li>-->
						<li><a href="/search_profile/search">Search</a>
						</li>
						<% if session[:current_user_key] %>
							<li><a href="/show_profile">My Profile</a></li>
						<% end %>
					</ul>
				</div>
				
				<!--login/logout buttons on the navbar-->
				
				<div class="login-header-block">
					<div class="login_block">
						<% if session[:current_user_key] %>
						<%= link_to 'Log out', logout_path, method: :get, :class => "btn color-1 size-2 hover-2" %>
						<% else %>
						<%= link_to 'Log in', login_path, method: :post, :class => "btn btn-login color-1 size-2 hover-2" %>
						<% end %>
					</div>	
				</div>
			</div>
		</div>
	</header>
	
	
	<!-- MAIN CONTENT -->
	<div id="content-block">
		<div class="container be-detail-container">
			<div class="info-block style-3">
			<div class="be-large-post-align "><h3 class="info-block-label">Search Results</h3></div>
		</div>
		<div class="container-fluid custom-container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div id="container-mix"  class="row _post-container_">
						<% @users.each do |info| %>
							<div class="category-1 mix custom-column-5">
								<div class="be-post">
									<a href="<%= show_profile_show_profile_path(:user_key => info.userKey) %>" class="be-img-block">
									<% if info.profile_picture? %>
									<img src="<%= info.profile_picture.url %>" alt="omg">
									<% else %>
                                    <img class="profile-img" src="<%= asset_path 'avatar-icon.png' %>" alt="">
									<% end %>
									</a>
									<a href="<%= show_profile_show_profile_path(:user_key => info.userKey) %>" class="be-post-title"><%= info.first_name %> <%= info.last_name %><br><%= info.attribute_values[:job_name] %><br><%=info.city + ", " + info.state%></a>
								</div>
							</div>
						<% end %>
					</div>
				</div>

			</div>
		</div>
		</div>
	</div>
	<footer>	
		<div class="footer-main">
			<div class="container-fluid custom-container">
				<div class="row">	
					<div class="col-md-3 col-xl-4">
						<div class="footer-block">
							<h1 class="footer-title">About Us</h1>
							<p>FashioNXT creates innovative fashion experiences and the creative edge in lifestyle technology.</p>
							<ul class="soc_buttons">
								<li><a href="https://www.facebook.com/FASHIONXtONLINE/"><i class="fa fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/fashionxtonline"><i class="fa fa-twitter"></i></a></li>
								<li><a href="https://www.pinterest.com/fashionxtonline/"><i class="fa fa-pinterest"></i></a></li>
								<li><a href="https://www.instagram.com/fashionxtonline/"><i class="fa fa-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/company/fashionxt/"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-6 col-xl-2">
						<div class="footer-block">
							<h1 class="footer-title">Some Links</h1>
							<div class="row footer-list-footer">
							<div class="col-md-6">
							<ul class="link-list">
                                <li><a href="https://fashionxt.com/agency/">About Us</a></li>
                                <li><a href="https://fashionxt.com/contact/">Help</a></li>
                                <li><a href="https://fashionxt.com/contact/">Contacts</a></li>
                                <li><a href="https://www.linkedin.com/company/fashionxt/jobs/">Job</a></li>
							</ul></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container-fluid custom-container">
				<div class="col-md-12 footer-end clearfix">
					<div class="left">
						<span class="copy">© 2018. All rights reserved. <span class="white"><a href="fashionxt.com"> FashioNXT</a></span></span>
						<span class="created">Created with LOVE by <span class="white"><a href=""> ThatSoftwareEngineeringGroup</a></span></span>
					</div>
				</div>			
			</div>
		</div>		
	</footer>

	<div class="be-fixed-filter"></div>
	<%= form_for :login_info, :action => 'login_submit', :url => login_info_login_submit_path do |form| %>
	<div class="large-popup login">
		<div class="container large-popup-container">
			<div class="row">
				<div class="col-md-8 col-md-push-2 col-lg-6 col-lg-push-3  large-popup-content">
					<div class="row">
						<div class="col-md-12">
							<i class="fa fa-times close-button"></i>
							<h5 class="large-popup-title">Log in</h5>
						</div>
						<form action="#" class="popup-input-search" method="post">
						<div class="col-md-6">
							<%= form.text_field :email, :class => 'input-signtype', :id => 'email', :placeholder => 'Your Email', :required => ''%>
							<!--<input class="input-signtype" type="email" required="" placeholder="Your email">-->
						</div>
						<div class="col-md-6 form-group">
							<%= form.password_field :password, :class => 'input-signtype', :id => 'password', :placeholder => 'Your Password', :required => '' %>
							<!--<input id= "password" class="input-signtype" type="password" required="" placeholder="Password">-->
						</div>
						<div class="col-xs-6"></div>
						<div class="col-xs-6 for-signin">
							<%= form.submit "SIGN IN", :class => 'be-popup-sign-button', :type => 'submit' %>
							<!--<input type="submit" class="be-popup-sign-button" value="SIGN IN">-->
						</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<!-- SCRIPT	-->
	<script src="<%= asset_path "jquery.min.js"%>"></script>
	<script src="<%= asset_path "jquery-ui.js"%>"></script>
	<script src="<%= asset_path "bootstrap.min.js"%>"></script>		
	<script src="<%= asset_path "idangerous.swiper.min.js"%>"></script>
	<script src="<%= asset_path "jquery.mixitup.js"%>"></script>
	<script src="<%= asset_path "jquery.viewportchecker.min.js"%>"></script>
	<script src="<%= asset_path "global.js"%>"></script>
	</body>
</html>