config/routes.rb
Rails.application.routes.draw do
  get 'general_info/:id/profile', to: 'general_info#profile', as: 'profile'
  # to retrive states and cities
  get 'messages', to: 'room#index'
  get 'states/:country_id', to: 'states#index', as: 'states'
  get 'cities/:state_id', to: 'cities#index', as: 'cities'
  post 'general_info/generate_about_me', to: 'general_info#generate_about_me', as: :generate_about_me

  post '/dm/:id', to: 'room#create_message'

  get '/dm', to: 'room#show'

  get '/dm/:id', to: 'room#show'

  get 'galleries/new' => 'galleries#new', :as => 'galleries/newg'

  get 'galleries/private_info/:id' => 'galleries#private_info'

  #get 'galleries/create'

  get 'galleries/destroy/:id'=> 'galleries#destroy', :as => 'galleries_destroy'

  get 'show_profile/destroy/:id'=> 'show_profile#destroy', :as => 'show_profile_destroy'

  get 'galleries/delete/:id'=> 'galleries#delete', :as => 'galleries_delete'

  get 'galleries/index'

  get 'galleries/show' => 'galleries#show', :as => 'galleries/show'

  post 'galleries/update' => 'galleries#update', :as => 'galleries/update'

  post 'galleries/create' => 'galleries#create', :as => 'galleries/create'

  # NXTFolio : Added in Spring 2023 for tagging feature
  post '/galleries/:id/create_tagging', to: 'galleries#create_tagging', as: 'create_tagging_gallery'
  delete '/galleries/:id/destroy_tagging', to: 'galleries#destroy_tagging', as: 'destroy_tagging_gallery'

  # spring2023 add/delete images in gallery
  get '/galleries/:id/edit', to: 'galleries#edit', as: 'edit_gallery'
  get '/galleries/:id/show', to: 'galleries#show', as: 'gallery'

  put '/galleries/:id/show', to: 'galleries#update', as: 'gallery/update'


  get '/galleries/:id/delete/:idx', to: 'galleries#delete', as: 'gallery_delete'

  get '/galleries/:id/add_images', to: 'galleries#transfer', as: 'gallery_added_image'

  # Fall 2023: To add comments
  get '/galleries/:id/comments', to: 'galleries#add_comment', as: 'gallery_add_comment'
  post '/galleries/:id/comments', to: 'galleries#post_comment', as: 'gallery_post_comment'

  # Winter 2024: To add tags
  get '/galleries/:id/tags', to: 'galleries#add_tag', as: 'gallery_add_tag'
  post '/galleries/:id/tags', to: 'galleries#create_tag', as: 'gallery_create_tag'

  #get 'template/create'
  #post 'template/create' => 'template#create', :as => 'template/create1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                   registrations: "users/registrations",
                                   sessions: "devise/sessions" }, 
                    skip: [:registrations] 
  get 'general_info_list' => 'general_info#list', :as => 'general_info_list'
  get 'general_info_save' => 'general_info#save', :as => 'general_info_save'
  get 'general_info/edit' => 'general_info#edit', :as => 'general_info/edit'
  get 'general_info/edit2' => 'general_info#edit2', :as => 'general_info/edit2'
  get 'general_info/edit_travel' => 'general_info#edit_travel', :as => 'general_info/edit_travel'
  get 'general_info/new', to: 'general_info#new', as: 'general_info_new'
  get 'general_info/new2' => 'general_info#new2', :as => 'general_info/new2'
  post 'general_info/update' => 'general_info#update', :as => 'general_info/update'
  get 'general_info/edit_profession' => 'general_info#edit_profession', :as => 'general_info/edit_profession'
  post 'general_info/update_profession' => 'general_info#update_profession', :as => 'general_info/update_profession'
  get 'general_info/profession_specific' => 'general_info#profession_specific', :as => 'general_info/profession_specific'
  post 'general_info/profession_specific' => 'general_info#profession_specific_create', :as => 'general_info/profession_specific_create'
  # Follow Feature
  get 'general_info/follow/:id' => 'general_info#follow'
  get 'general_info/unfollow/:id' => 'general_info#unfollow'

  namespace :admin do
    get '/' => 'admin#landing'
    get '/create' => 'admin#create'
    post '/create' => 'admin#create'
    get '/edit' => 'admin#edit'
    post '/edit' => 'admin#edit'  
    get '/delete' => 'admin#delete'
    post '/delete' => 'admin#delete'
  end

  namespace :api do
    get 'users', to: 'general_info#index'
    get 'delete/:id', to: 'general_info#delete'
    get 'toggle_access/:id', to: 'general_info#toggle_access'
    # resources :general_info, only: [:index]
  end

  get '/general_info/make_admin/:user' => 'general_info#make_admin'

  get 'edit_job' => 'edit_job#edit'
  post 'edit_job' => 'edit_job#update'
  patch 'edit_job/update' => 'edit_job#update'
  post 'edit_job/update' => 'edit_job#update'
  get 'login_info_list' => 'login_info#list', :as => 'login_info_list'
  get 'login_info/login' => 'login_info#login', :as => 'login_info/login'
  post 'login_info/login_submit' => 'login_info#login_submit', :as => 'login_info/login_submit'
  get 'login_info/logout' => 'login_info#logout', :as => 'login_info/logout'
  post 'login_info/new' => 'login_info#new', :as => 'login_info/new'
  post 'login_info/create' => 'login_info#create', :as => 'login_info/create'
  get 'login_info/edit' => 'login_info#edit', :as => 'login_info/edit'
  post 'login_info/update' => 'login_info#update', :as => 'login_info/update'
  get 'unconfirmed_user/new' => 'unconfirmed_user#new', :as => 'unconfirmed_user/new'
  post 'unconfirmed_user/verify' => 'unconfirmed_user#verify', :as => 'unconfirmed_user/verify'
  get 'unconfirmed_user/regenerate_token' => 'unconfirmed_user#regenerate_token', :as => 'unconfirmed_user/regenerate_token'


  get 'login' => 'login_info#login', :as => 'login'
  get  'logout' => 'login_info#logout', :as => 'logout'
  # post 'create' => 'login_info#create', :as => 'create'


  get 'specific_designer_list' => 'specific_designer#list', :as => 'specific_designer_list'
  get 'specific_designer/edit' => 'specific_designer#edit', :as => 'specific_designer/edit'
  post 'specific_designer/update' => 'specific_designer#update', :as => 'specific_designer/update'
  delete 'specific_designer/destroy' => 'specific_designer#destroy', :as => 'specific_designer/destroy'

  get 'specific_model_list' => 'specific_model#list', :as => 'specific_model_list'
  get 'specific_model/edit' => 'specific_model#edit', :as => 'specific_model/edit'
  post 'specific_model/update' => 'specific_model#update', :as => 'specific_model/update'
  delete 'specific_model/destroy' => 'specific_model#destroy', :as => 'specific_model/destroy'

  get 'specific_photographer_list' => 'specific_photographer#list', :as => 'specific_photographer_list'
  get 'specific_photographer/edit' => 'specific_photographer#edit', :as => 'specific_photographer/edit'
  post 'specific_photographer/update' => 'specific_photographer#update', :as => 'specific_photographer/update'
  delete 'specific_photographer/destroy' => 'specific_photographer#destroy', :as => 'specific_photographer/destroy'

  get 'show_profile/mymodel' => 'show_profile#show_model', :as => 'show_profile_show_model'
  get 'show_profile' => 'show_profile#show_profile', :as => 'show_profile_show_profile'

  get 'search_profile/show' => 'search_profile#show', :as => 'search_profile/show'
  get 'search_profile/search' => 'search_profile#search', :as => 'search_profile/search'
  get 'search_profile/search_general' => 'search_profile#search_general', :as => 'search_profile/search_general'
  get 'search_profile/search_job' => 'search_profile#search_job', :as => 'search_profile/search_job'

  get 'search_profile/search_login' => 'search_profile#search_login', :as => 'search_profile/search_login'

  get 'search_profile/search_model' => 'search_profile#search_model', :as => 'search_profile/search_model'
  get 'search_profile/search_photographer' => 'search_profile#search_photographer', :as => 'search_profile/search_photographer'
  get 'search_profile/search_specific' => 'search_profile#search_specific', :as => 'search_profile/search_specific'
  get 'search_profile/search_specific_model' => 'search_profile#search_specific_model', :as => 'search_profile/search_specific_model'
  get 'search_profile/search_specific_photographer' => 'search_profile#search_specific_photographer', :as => 'search_profile/search_specific_photographer'
  get 'search_profile/show_profile/:id' => 'search_profile#show_profile', :as => 'search_profile/show_profile'
  get 'add_profession' => 'template#index', :as => 'template'
  post '/' => 'general_info#index', :as => 'general_info_index_post'

  get 'application/index' => 'application#index', :as => 'application/index'

  get 'search_engine/show' => 'search_engine#show', :as => 'search_engine/show'
  get 'search_engine/search' => 'search_engine#search', :as => 'search_engine/search'

  get 'job_search/jobshow' => 'job_search#jobshow', :as => 'job_search/jobshow'
  #get 'job_search/jobsearch' => 'job_search#jobsearch', :as => 'job_search/jobsearch'

  # get 'job_info/post_job' => 'job_info#post_job', :as => 'job_info/post_job1'
  post '/job_info/post_job', to: 'job_info#post_job', as: 'job_info_post_job'
  get 'job_info/index',   to: 'job_info#index',  as: 'job_info/index'
  get 'job_info/search', to: 'job_info#search', as: 'job_info/search'
  get 'job_info/new_job', to: 'job_info#new_job', as: 'job_info_new_job'
  get 'job_info/show/:id', to: 'job_info#show', as: 'job_info_show'
  # delete 'job_info/:id/del(.:format)', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/del', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/visitor', to: 'job_info#visitor_show', as: 'visitor_job_info'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Defines the root path route ("/")

app/models/login_info.rb
class LoginInfo < ApplicationRecord
  validates_presence_of :email
  validates_presence_of :password
  validates_confirmation_of :password
  validate :password_requirements_are_met #not needed for FB or Google login
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_uniqueness_of :email
  validates :email, presence: true

  attr_accessor :password_confirmation

  def self.search(searchArg)
    if searchArg[:email_regex].nil? || searchArg[:email_regex].empty?
      return LoginInfo.where("email ILIKE ?", searchArg[:email])
    end

    if searchArg[:email_regex].present? && searchArg[:email].present?
      case searchArg[:email_regex]
      when 'Contains'
        searchArg[:email] = "%#{searchArg[:email]}%"
      when 'Starts With'
        searchArg[:email] = "#{searchArg[:email]}%"
      when 'Ends With'
        searchArg[:email] = "%#{searchArg[:email]}"
      when 'Exactly Matches'
        searchArg[:email] = searchArg[:email]
      end
    else
      searchArg[:email] = "%"
    end

    LoginInfo.where("email ILIKE ?", searchArg[:email])
  end

  def password_requirements_are_met
    rules = {
      " must be at least 8 characters long"          => /.{8,}/,
      " must contain at least one uppercase letter"  => /[A-Z]+/,
      " must contain at least one special character" => /[^A-Za-z0-9]+/,
      " must contain at least one digit"             => /\d+/,
      " must contain at least one lowercase letter"  => /[a-z]+/
    }

    if password.nil?
      errors.add(:password, " must be at least 8 characters long")
    else
      rules.each do |message, regex|
        errors.add(:password, message) unless password.match(regex)
      end
    end
  end

  def validate_pwd
    validate :password_requirements_are_met #not needed for FB or Google sign up
  end
end

app/controllers/login_info_controller.rb
class LoginInfoController < ApplicationController
  # Variable that holds a params/object with all the attributes filled in
  def list
    @login_infos = LoginInfo.all
  end

  def show
    @login_info = LoginInfo.find(params[:id])
  end

  # Associated with the view used for create
  def new
    @login_info = LoginInfo.new
  end

  # Create is called upon for the 1st part of profile creation
  def create
    @login_info = LoginInfo.new(login_info_params)
    if LoginInfo.exists?(:email => @login_info[:email])
      flash[:error] = "Email already exists."
      redirect_to login_info_new_path and return
    end

    # Checks for mismatched & unentered passwords before saving LoginInfo object to database
    # field value required in HTML, hence this check not required
    # unless @login_info[:password] != "" && login_info_params[:password_confirmation] != ""
    #   flash[:notice] = "Enter your password! Please try again."
    #   redirect_to login_info_login_path and return
    # end
    
    unless @login_info[:password] == login_info_params[:password_confirmation]
      #@login_info.userKey = SecureRandom.hex(10)
      flash[:error] = "Passwords don't match! Please try again."
      redirect_to login_info_new_path and return
    end

    unless @login_info.validate_pwd == true
      flash[:error] = "#{@login_info.errors.full_messages.first}"
      redirect_to login_info_new_path and return
    end
    # @unconfirmed_user.verification_email
    @user = UnconfirmedUser.find_by(unconfirmed_email: @login_info.email)
    if @user.present?
      flash[:notice] = 'We have already sent you a code to verify your email. Please check your inbox and spam!'
      redirect_to unconfirmed_user_new_path and return
    end
    UnconfirmedUser.create!(
      unconfirmed_email: @login_info.email,
      encrypted_password: @login_info.password,
      confirmation_token: SecureRandom.random_number(1000000).to_s.rjust(6, '0'),
      confirmation_sent_at: Time.current
    )
    
    EmailVerificationMailer.verification_email(UnconfirmedUser.last).deliver_now!
    session[:current_login_user] = @login_info
    redirect_to unconfirmed_user_new_path, notice: 'We have sent you a new code to verify the email. Please verify your email and continue your registration!'
  end

  # Params used to create the LoginInfo object
  def login_info_params
    params.require(:login_info).permit(:email, :password, :password_confirmation)
    # params.require(:sign_in_up).permit(:email, :password, :password_confirmation)
  end

  # Allows room to edit the login_info_params of the LoginInfo object
  # Displays information pulled from database that matches the session key of the current room
  # Associated with the view used for update
  def edit
    if LoginInfo.exists?(:userKey => session[:current_user_key])
      @login_info = LoginInfo.find_by(userKey: session[:current_user_key])
    end
  end

  # Saves the edit of the LoginInfo object to the database
  def update
    @login_info = LoginInfo.find_by(userKey: session[:current_user_key])

    if login_info_params[:password] == login_info_params[:password_confirmation]
      # if @login_info.update_attributes(login_info_params)
      if @login_info.update(login_info_params)
        redirect_to '/show_profile'
      else
        render :action => 'edit'
      end
    else
      flash[:error] = "Passwords don't match!"
      render :action => 'edit'
    end
  end

  # Not implemented   
  def delete
  end

  # Associated with the view used for login_submit
  def login
    @login_info = LoginInfo.new
    #render :template => :'new/login'
  end

  # Checks the email & password input against existing LoginInfo objects in database
  # Sets the session key of the current room if match found
  # Else displays error message
  def login_submit
    @login_info = LoginInfo.new(login_info_param)
    if LoginInfo.exists?(:email => @login_info[:email])
      @login_user = LoginInfo.find_by(email: @login_info[:email])
      
      if @login_user[:password] == @login_info[:password]
        #login

        if not @login_user[:enabled]
          flash[:notice] = 'This accound is currently disabled'
          redirect_to login_info_login_path
        else
          session[:current_user_key] = @login_user[:userKey]
          session[:login_time] = Time.current # Spring 2023

          if @login_user[:is_admin] != nil
            session[:is_admin] = true
          end
          flash[:success] = "You Have Successfully Logged In! Welcome Back!"

          # create/update record in the user_activity_details table
          current_user = GeneralInfo.find_or_create_by(userKey: session[:current_user_key])
          redirect_to root_path
        end
      else
        flash[:error] = "The Credentials You Provided Are Not Valid. Please Try Again."
        redirect_to login_info_login_path
      end
    else
      flash[:error] = "The Credentials You Provided Are Not Valid. Please Try Again."
      # redirect_to login_info_login_path
      redirect_to login_info_login_path
    end
  end

  # Params used to find the LoginInfo object in the database
  def login_info_param
    params.require(:login_info).permit(:email, :password)
  end

  # Removes the session key of the current room
  def logout
    session[:current_user_key] = nil
    session[:is_admin] = false
    session.delete(:login_time)
    flash[:success] = "You Have Successfully Logged Out! Hope To See You Soon!"
    $current_user = nil #for facebook login usecase
    # redirect_to destroy_user_session_path
    redirect_to destroy_user_session_path
  end
end

app/helpers/login_info_helper.rb
module LoginInfoHelper
end

app/views/login_info/edit.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>FashioNXT</title>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="<%= asset_path "favicon.jpg"%>">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="<%= asset_path "bootstrap.min.css"%>">
		<link rel="stylesheet" href="<%= asset_path "icon.css"%>">
		<link rel="stylesheet" href="<%= asset_path "loader.css"%>">
		<link rel="stylesheet" href="<%= asset_path "idangerous.swiper.css"%>">
		<link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
		<link rel="stylesheet" href="<%= asset_path "stylesheet.css"%>">
		
	</head>
	<body data-spy="scroll" data-target="blog-detail-2.htmlscrollspy">
	

	<!-- THE LOADER -->

	<div class="be-loader">
    	<div class="spinner">
			<img id="spinner-img" src="<%= asset_path "logo.png"%>"  alt="">
			<p class="circle">
			  <span class="ouro">
			    <span class="left"><span class="anim"></span></span>
			    <span class="right"><span class="anim"></span></span>
			  </span>
			</p>
		</div>
    </div>
	<!-- THE HEADER -->
  <%= render 'shared/header' %>
	
	
	<!-- MAIN CONTENT -->
	<div id="content-block">
	  <div class="large-popup-fixed"></div>
    <% if flash[:notice] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong><%= flash[:notice]%></strong>
      </div>
      </div>
    <% elsif flash[:success] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible" style="background-color: rgba(4, 199, 4, 0.2);">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong><%= flash[:success]%></strong>
      </div>
      </div>
    <% elsif flash[:error] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible" style="background-color: rgba(255, 0, 0, 0.2);">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong><%= flash[:error]%></strong>
      </div>
      </div>
    <% end %>
		<div class="container be-detail-container">
		  
			<div class="row">
				<div class="col-xs-12 col-sm-12 _editor-content_">
					<div class="sec"  data-sec="basic-information">
						<div class="be-large-post">
							<div class="info-block style-2">
								<div class="be-large-post-align ">
									<h3 class="info-block-label">Change Password</h3>
								</div>
							</div>
							<div class="be-large-post-align">
								<div class="row">
								  <%= form_for @login_info, :action => 'update', :url => login_info_update_path do |f| %>
												<div class="input-col col-xs-12 col-sm-6">
													<div class="form-group fg_icon focus-2">
														<%= f.text_field :email, :class => 'form-input', :placeholder => 'Enter your email', :readonly => true%>
													</div>							
												</div>
												<div class="input-col col-xs-12 col-sm-6">
													<div class="form-group fg_icon focus-2">
														<%= f.text_field :password, :class => 'form-input', :placeholder => 'Enter your new password', :type => 'password'%>
													</div>							
												</div>
												<div class="input-col col-xs-12 col-sm-6">
													<div class="form-group fg_icon focus-2">
														<%= f.text_field :password_confirmation, :class => 'form-input', :placeholder => 'Re-enter your new password', :type => 'password'%>
													</div>							
												</div>
											<div class="col-xs-12 col-sm-3">
												<%= f.submit "SAVE", :class => 'btn full color-1 size-1 hover-1' %>
											</div>
											<div class="input-col col-xs-12 col-sm-4">
												<div class="be-vidget back-block">
													<a class="btn full color-1 size-1 hover-1" href="/show_profile" method="get">Cancel</a>
												</div>
											</div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>	
				
			</div>
		</div>
	</div>
	<%= render 'shared/footer' %>

	<div class="be-fixed-filter"></div>
	<!-- SCRIPT	-->
	<script src="<%= asset_path "jquery.min.js"%>"></script>
	<script src="<%= asset_path "jquery-ui.js"%>"></script>
	<script src="<%= asset_path "bootstrap.min.js"%>"></script>		
	<script src="<%= asset_path "idangerous.swiper.min.js"%>"></script>
	<script src="<%= asset_path "jquery.mixitup.js"%>"></script>
	<script src="<%= asset_path "jquery.viewportchecker.min.js"%>"></script>
	<script src="<%= asset_path "global.js"%>"></script>
	</body>
</html>

app/views/login_info/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashioNXT</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="shortcut icon" href="<%= asset_path "favicon.jpg"%>">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="<%= asset_path "bootstrap.min.css"%>">
  <link rel="stylesheet" href="<%= asset_path "icon.css"%>">
  <link rel="stylesheet" href="<%= asset_path "loader.css"%>">
  <link rel="stylesheet" href="<%= asset_path "idangerous.swiper.css"%>">
  <link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
  <link rel="stylesheet" href="<%= asset_path "stylesheet.css"%>">
  <link rel="stylesheet" href="<%= asset_path "profile.css"%>">
  <link rel="stylesheet" href="<%= asset_path "search_button.css"%>">

</head>
<div >

<!-- THE LOADER -->

<div class="be-loader">
  <div class="spinner">
    <img id="spinner-img" src="<%= asset_path "logo.png"%>"  alt="">
    <p class="circle">
			  <span class="ouro">
			    <span class="left"><span class="anim"></span></span>
			    <span class="right"><span class="anim"></span></span>
			  </span>
    </p>
  </div>
</div>

<!-- THE HEADER -->

<%= render 'shared/header' %>

<!-- MAIN CONTENT -->
<div id="content-block">
  <div class="head-bg">
    <div class="head-bg-img"></div>

    <div class="large-popup-fixed"></div>
    <% if flash[:notice] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong><%= flash[:notice]%></strong>
      </div>
      </div>
    <% elsif flash[:success] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible" style="background-color: rgba(4, 199, 4, 0.2);">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong><%= flash[:success]%></strong>
      </div>
      </div>
    <% elsif flash[:error] %>
      <div class="alert-container col-md-12">
      <div class="alert style-3 alert-dismissible" style="background-color: rgba(255, 0, 0, 0.2);">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong><%= flash[:error]%></strong>
      </div>
      </div>
    <% end %>


    <div class="head-bg-content">
      <div class="col-md-12">

        <!-- Log In -->
        <div class="col-md-12">
          <h1>Log In</h1>
          <div class="row-fluid" id="log_in_div">
            <%= form_for :login_info, :action => 'login_submit', :url => login_info_login_submit_path do |form| %>
              <form action="#" class="popup-input-search" method="post">
                <div class="span3" id = "email">
                  <%= form.text_field :email, :class => 'input-signtype', :id => 'login_email', :placeholder => 'Your Email', :required => ''%>
                </div>
                <br>
                <div class="span3">
                  <%= form.password_field :password, :class => 'input-signtype', :id => 'login_password', :placeholder => 'Your Password', :required => '' %>
                </div>
                <br>
                <div class="span3 for-signin">
                <div class="d-flex flex-column align-items-center">
                  <%= form.submit "SIGN IN", class: "btn color-1 size-1 hover-1", :type => 'submit' %>
                </div>
              </form>
            <% end %>
            <br>
            <%= link_to "Forgot your password?", password_reset_path, :class => 'forgot' %>
            &emsp;|&emsp;
            <%= link_to "New user? Sign Up Here!", new_user_registration_path, :class => 'forgot' %>
          </div>
        </div>
      </div>
   </div> <!-- bg head content -->
  </div>
</div>

  <!-- THE FOOTER -->
  <%= render 'shared/footer' %>

  <!-- SCRIPTS	 -->
  <script src="<%= asset_path "jquery.min.js"%>"></script>
  <script src="<%= asset_path "jquery-ui.js"%>"></script>
  <script src="<%= asset_path "bootstrap.min.js"%>"></script>
  <script src="<%= asset_path "idangerous.swiper.min.js"%>"></script>
  <script src="<%= asset_path "jquery.mixitup.js"%>"></script>
  <script src="<%= asset_path "jquery.viewportchecker.min.js"%>"></script>
  <script src="<%= asset_path "global.js"%>"></script>
  <script src="<%= asset_path "application.js"%>"></script>

</div>
</body>
</html>