config/routes.rb
Rails.application.routes.draw do
  get 'general_info/:id/profile', to: 'general_info#profile', as: 'profile'
  # to retrive states and cities
  get 'messages', to: 'room#index'
  get 'states/:country_id', to: 'states#index', as: 'states'
  get 'cities/:state_id', to: 'cities#index', as: 'cities'
  post 'general_info/generate_about_me', to: 'general_info#generate_about_me', as: :generate_about_me

  post '/dm/:id', to: 'room#create_message'

  get '/dm', to: 'room#show'

  get '/dm/:id', to: 'room#show'

  get 'galleries/new' => 'galleries#new', :as => 'galleries/newg'

  get 'galleries/private_info/:id' => 'galleries#private_info'

  #get 'galleries/create'

  get 'galleries/destroy/:id'=> 'galleries#destroy', :as => 'galleries_destroy'

  get 'show_profile/destroy/:id'=> 'show_profile#destroy', :as => 'show_profile_destroy'

  get 'galleries/delete/:id'=> 'galleries#delete', :as => 'galleries_delete'

  get 'galleries/index'

  get 'galleries/show' => 'galleries#show', :as => 'galleries/show'

  post 'galleries/update' => 'galleries#update', :as => 'galleries/update'

  post 'galleries/create' => 'galleries#create', :as => 'galleries/create'

  # NXTFolio : Added in Spring 2023 for tagging feature
  post '/galleries/:id/create_tagging', to: 'galleries#create_tagging', as: 'create_tagging_gallery'
  delete '/galleries/:id/destroy_tagging', to: 'galleries#destroy_tagging', as: 'destroy_tagging_gallery'

  # spring2023 add/delete images in gallery
  get '/galleries/:id/edit', to: 'galleries#edit', as: 'edit_gallery'
  get '/galleries/:id/show', to: 'galleries#show', as: 'gallery'

  put '/galleries/:id/show', to: 'galleries#update', as: 'gallery/update'


  get '/galleries/:id/delete/:idx', to: 'galleries#delete', as: 'gallery_delete'

  get '/galleries/:id/add_images', to: 'galleries#transfer', as: 'gallery_added_image'

  # Fall 2023: To add comments
  get '/galleries/:id/comments', to: 'galleries#add_comment', as: 'gallery_add_comment'
  post '/galleries/:id/comments', to: 'galleries#post_comment', as: 'gallery_post_comment'

  # Winter 2024: To add tags
  get '/galleries/:id/tags', to: 'galleries#add_tag', as: 'gallery_add_tag'
  post '/galleries/:id/tags', to: 'galleries#create_tag', as: 'gallery_create_tag'

  #get 'template/create'
  #post 'template/create' => 'template#create', :as => 'template/create1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                   registrations: "users/registrations",
                                   sessions: "devise/sessions" }, 
                    skip: [:registrations] 
  get 'general_info_list' => 'general_info#list', :as => 'general_info_list'
  get 'general_info_save' => 'general_info#save', :as => 'general_info_save'
  get 'general_info/edit' => 'general_info#edit', :as => 'general_info/edit'
  get 'general_info/edit2' => 'general_info#edit2', :as => 'general_info/edit2'
  get 'general_info/edit_travel' => 'general_info#edit_travel', :as => 'general_info/edit_travel'
  get 'general_info/new', to: 'general_info#new', as: 'general_info_new'
  get 'general_info/new2' => 'general_info#new2', :as => 'general_info/new2'
  post 'general_info/update' => 'general_info#update', :as => 'general_info/update'
  get 'general_info/edit_profession' => 'general_info#edit_profession', :as => 'general_info/edit_profession'
  post 'general_info/update_profession' => 'general_info#update_profession', :as => 'general_info/update_profession'
  get 'general_info/profession_specific' => 'general_info#profession_specific', :as => 'general_info/profession_specific'
  post 'general_info/profession_specific' => 'general_info#profession_specific_create', :as => 'general_info/profession_specific_create'
  # Follow Feature
  get 'general_info/follow/:id' => 'general_info#follow'
  get 'general_info/unfollow/:id' => 'general_info#unfollow'

  namespace :admin do
    get '/' => 'admin#landing'
    get '/create' => 'admin#create'
    post '/create' => 'admin#create'
    get '/edit' => 'admin#edit'
    post '/edit' => 'admin#edit'  
    get '/delete' => 'admin#delete'
    post '/delete' => 'admin#delete'
  end

  namespace :api do
    get 'users', to: 'general_info#index'
    get 'delete/:id', to: 'general_info#delete'
    get 'toggle_access/:id', to: 'general_info#toggle_access'
    # resources :general_info, only: [:index]
  end

  get '/general_info/make_admin/:user' => 'general_info#make_admin'

  get 'edit_job' => 'edit_job#edit'
  post 'edit_job' => 'edit_job#update'
  patch 'edit_job/update' => 'edit_job#update'
  post 'edit_job/update' => 'edit_job#update'
  get 'login_info_list' => 'login_info#list', :as => 'login_info_list'
  get 'login_info/login' => 'login_info#login', :as => 'login_info/login'
  post 'login_info/login_submit' => 'login_info#login_submit', :as => 'login_info/login_submit'
  get 'login_info/logout' => 'login_info#logout', :as => 'login_info/logout'
  post 'login_info/new' => 'login_info#new', :as => 'login_info/new'
  post 'login_info/create' => 'login_info#create', :as => 'login_info/create'
  get 'login_info/edit' => 'login_info#edit', :as => 'login_info/edit'
  post 'login_info/update' => 'login_info#update', :as => 'login_info/update'
  get 'unconfirmed_user/new' => 'unconfirmed_user#new', :as => 'unconfirmed_user/new'
  post 'unconfirmed_user/verify' => 'unconfirmed_user#verify', :as => 'unconfirmed_user/verify'
  get 'unconfirmed_user/regenerate_token' => 'unconfirmed_user#regenerate_token', :as => 'unconfirmed_user/regenerate_token'


  get 'login' => 'login_info#login', :as => 'login'
  get  'logout' => 'login_info#logout', :as => 'logout'
  # post 'create' => 'login_info#create', :as => 'create'


  get 'specific_designer_list' => 'specific_designer#list', :as => 'specific_designer_list'
  get 'specific_designer/edit' => 'specific_designer#edit', :as => 'specific_designer/edit'
  post 'specific_designer/update' => 'specific_designer#update', :as => 'specific_designer/update'
  delete 'specific_designer/destroy' => 'specific_designer#destroy', :as => 'specific_designer/destroy'

  get 'specific_model_list' => 'specific_model#list', :as => 'specific_model_list'
  get 'specific_model/edit' => 'specific_model#edit', :as => 'specific_model/edit'
  post 'specific_model/update' => 'specific_model#update', :as => 'specific_model/update'
  delete 'specific_model/destroy' => 'specific_model#destroy', :as => 'specific_model/destroy'

  get 'specific_photographer_list' => 'specific_photographer#list', :as => 'specific_photographer_list'
  get 'specific_photographer/edit' => 'specific_photographer#edit', :as => 'specific_photographer/edit'
  post 'specific_photographer/update' => 'specific_photographer#update', :as => 'specific_photographer/update'
  delete 'specific_photographer/destroy' => 'specific_photographer#destroy', :as => 'specific_photographer/destroy'

  get 'show_profile/mymodel' => 'show_profile#show_model', :as => 'show_profile_show_model'
  get 'show_profile' => 'show_profile#show_profile', :as => 'show_profile_show_profile'

  get 'search_profile/show' => 'search_profile#show', :as => 'search_profile/show'
  get 'search_profile/search' => 'search_profile#search', :as => 'search_profile/search'
  get 'search_profile/search_general' => 'search_profile#search_general', :as => 'search_profile/search_general'
  get 'search_profile/search_job' => 'search_profile#search_job', :as => 'search_profile/search_job'

  get 'search_profile/search_login' => 'search_profile#search_login', :as => 'search_profile/search_login'

  get 'search_profile/search_model' => 'search_profile#search_model', :as => 'search_profile/search_model'
  get 'search_profile/search_photographer' => 'search_profile#search_photographer', :as => 'search_profile/search_photographer'
  get 'search_profile/search_specific' => 'search_profile#search_specific', :as => 'search_profile/search_specific'
  get 'search_profile/search_specific_model' => 'search_profile#search_specific_model', :as => 'search_profile/search_specific_model'
  get 'search_profile/search_specific_photographer' => 'search_profile#search_specific_photographer', :as => 'search_profile/search_specific_photographer'
  get 'search_profile/show_profile/:id' => 'search_profile#show_profile', :as => 'search_profile/show_profile'
  get 'add_profession' => 'template#index', :as => 'template'
  post '/' => 'general_info#index', :as => 'general_info_index_post'

  get 'application/index' => 'application#index', :as => 'application/index'

  get 'search_engine/show' => 'search_engine#show', :as => 'search_engine/show'
  get 'search_engine/search' => 'search_engine#search', :as => 'search_engine/search'

  get 'job_search/jobshow' => 'job_search#jobshow', :as => 'job_search/jobshow'
  #get 'job_search/jobsearch' => 'job_search#jobsearch', :as => 'job_search/jobsearch'

  # get 'job_info/post_job' => 'job_info#post_job', :as => 'job_info/post_job1'
  post '/job_info/post_job', to: 'job_info#post_job', as: 'job_info_post_job'
  get 'job_info/index',   to: 'job_info#index',  as: 'job_info/index'
  get 'job_info/search', to: 'job_info#search', as: 'job_info/search'
  get 'job_info/new_job', to: 'job_info#new_job', as: 'job_info_new_job'
  get 'job_info/show/:id', to: 'job_info#show', as: 'job_info_show'
  # delete 'job_info/:id/del(.:format)', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/del', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/visitor', to: 'job_info#visitor_show', as: 'visitor_job_info'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Defines the root path route ("/")

app/views/layout/_appendcategory.html.erb
<div class="btn-group" id="category">
  <div class="be-large-post-align text-center">
    <h2 class="info-block-label">Creators</h2>
  </div>
  <button id="Model">Model</button>
  <button id="Photographer">Photographer</button>
  <button id="Everyone">All</button>

  <button id="append">Profession1</button>
  <button id="append">Profession2</button>
  <button id="append">Profession3</button>
</div>

app/views/layout/_body.html.erb
<script type="application/javascript"></script>

app/views/layout/_footer.html.erb
<!-- Map Section -->

<!-- Footer -->
<footer>
  <div class="container text-center">
    <p>Copyright &copy; FashioNXT</p>
  </div>
</footer>

app/views/layout/_form.html.erb
<div class="skillsForm">
  <%= label_tag 'tag' %>
  <%= text_field_tag 'tags[]' %>
  <%= label_tag 'weight' %>
  <%= text_field_tag 'weights[]' %>
</div>

app/views/layout/_header.erb
<!--/ LAYOUT HEADER FILE
-->
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title href="/">FashionNXT - Your one stop shop for fashion</title>

  <!-- Bootstrap Core CSS -->
  <link href="<%= asset_path 'bootstrap.css' %>" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

  <!-- Theme CSS -->
  <link href="<%= asset_path 'grayscale.css' %>" rel="stylesheet">
  <link href="<%= asset_path 'navbar.css.erb' %>" rel="stylesheet">

  <style>
    body {
      width: 100%;
      height: 100%;
      font-family: "acumin-pro", "Acumin Pro", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <% if @landing %>
      color: white;
      background-color: black;
    <% else %>
      color: black;
      background-color: white;
    <% end %>
    }

    @media (min-width: 768px) {
      .navbar-custom {
      <% if @landing %>
        background: transparent;
      <% else %>
        background: rgba(0, 0, 0, 0.6);
      <% end %>
      }
    }
  </style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

app/views/layout/_header.html.erb
<!--/ LAYOUT HEADER FILE
-->
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title href="/">FashionNXT - Your one stop shop for fashion</title>

  <!-- Bootstrap Core CSS -->
  <link href="<%= asset_path 'bootstrap.css' %>" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

  <!-- Theme CSS -->
  <link href="<%= asset_path 'grayscale.css' %>" rel="stylesheet">
  <link href="<%= asset_path 'navbar.css.erb' %>" rel="stylesheet">

  <style>
      body {
          width: 100%;
          height: 100%;
          font-family: "acumin-pro", "Acumin Pro", "Helvetica Neue", Helvetica, Arial, sans-serif;
      <% if @landing %>
          color: white;
          background-color: black;
      <% else %>
          color: black;
          background-color: white;
      <% end %>
      }

      @media (min-width: 768px) {
          .navbar-custom {
          <% if @landing %>
              background: transparent;
          <% else %>
              background: rgba(0, 0, 0, 0.6);
          <% end %>
          }
      }
  </style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

app/views/layout/_homepage.html.erb
<link rel="stylesheet" href="<%= asset_path "search_button.css" %>">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div id="container-mix" class="row _post-container_">
        <div class="be-post branddiv" id="Brand1">
          <% if @gallery.present? %>
            <% @gallery.each do |gallery| %>
              <% modinfo = GeneralInfo.find(gallery.GeneralInfo_id) %>
              <% if modinfo.attribute_values[:job_name] == "Brand Owner" %>
                <div class="col-md-4">
                  <a class="be-img-block">
                    <div class="photo photo-type-line">
                      <% if modinfo.profile_picture? %>
                        <img src="<%= gallery.gallery_picture[0].url %>" alt="omg">
                      <% else %>
                        <img class="profile-img" src="<%= asset_path 'avatar-icon.png' %>">
                      <% end %>
                      <a class="photo-hover" href="<%= gallery_path(gallery.id) %>">
                        <div class="photo-info">
                          <div class="headline"><%= gallery.gallery_title %></div>
                          <div class="line"></div>
                          <div class="desc"><%= gallery.gallery_description %></div>
                          <div class="line"></div>
                          <% if gallery.reviews.blank? %>
                            <% average_review = 0 %>
                          <% else %>
                            <% average_review = gallery.reviews.average(:rating).round(2) %>
                          <% end %>
                          <div class="average-review-rating" data-score="<%= average_review %>">
                          </div>
                        </div>
                        <div class="mask"></div>
                      </a>
                    </div>
                  </a>
                  <div id="custom-project-title">
                    <a href="<%= show_profile_show_profile_path(user_key: modinfo.userKey) %>">
                      <%= modinfo.first_name %> <%= modinfo.last_name %>
                    </a>
                  </div>
                  <div id="custom-profile-name"><%= modinfo.job_name %></div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>

        <div>
          <h3>Projects you may be interested in:</h3>
          <% if session[:current_user_key] %>
            <% current_user = GeneralInfo.find_by(userKey: session[:current_user_key]) %>
            <% if current_user && current_user.gallery %>
              <% galleries = current_user.gallery %>
              <% galls = [] %>
              <% galleries.each do |gallery| %>
                <% gallery.get_similar_galleries.keys.each do |gal| %>
                  <% galls.push(gal) %>
                <% end %>
              <% end %>
              <% galls = galls.uniq %>
              <div class="gallery-wrapper" style="overflow: visible;">
                <div class="row">
                  <div class="gallery-pair">
                    <% galls.each do |gall| %>
                      <div class="col-md-4">
                        <a class="be-img-block">
                          <div class="photo photo-type-line">
                            <a class="photo-hover" href="<%= gallery_path(gall.id) %>">
                              <div class="photo-info">
                                <div class="headline"><%= gall.gallery_title %></div>
                                <div class="line"></div>
                                <div class="desc"><%= gall.gallery_description %></div>
                              </div>
                              <div class="mask"></div>
                            </a>
                              <div class="image">
                                <a class="be-img-block profile-img img-thumbnail">
                                  <img src="<%= gall.gallery_picture[0].url %>" alt="omg">
                                </a>
                              </div>
                            <div class="mask"></div>
                          </div>
                        </a>
                        <div class="headline"><a href="<%= gallery_path(gall.id) %>"><%= gall.gallery_title %></a></div>
                        <div class="desc"><%= gall.gallery_description %></div>
                        <% if gall.gallery_totalRate && gall.gallery_totalRator %>
                          <div class="desc">Rating: <%= (gall.gallery_totalRate / gall.gallery_totalRator).to_s %></div>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% else %>
              <p>No galleries available for the current user.</p>
            <% end %>
          <% else %>
            <% @all_galleries = Gallery.all %>
            <% map = {} %>
            <% if @all_galleries.present? %>
              <% @all_galleries.each do |gal| %>
                <% total ||= 0 %> 
                <% total = gal.reviews.sum { |review| review.rating || 0 }.to_i if gal.reviews.exists? %>
                <% count ||= 0 %>
                <% count = gal.reviews&.size || 0 %>
                <% gal.gallery_totalRate ||= total %>
                <% gal.gallery_totalRator ||= count %>
                <% if map.size < 50 && gal.gallery_totalRator > 0 && (gal.gallery_totalRate / gal.gallery_totalRator >= 3) %>
                  <% map[gal] = gal.gallery_totalRate / gal.gallery_totalRator %>
                <% end %>
              <% end %>
            <% end %>
            <% sorted_map = map.sort_by { |_, v| -v }.to_h %>
            <% if sorted_map.present? %>
              <div class="gallery-wrapper" style="overflow-y: visible;">
                <div class="row">
                  <% sorted_map.keys.each_slice(50) do |galls| %>
                    <div class="gallery-pair">
                      <% galls.each do |gall| %>
                        <div class="col-md-4">
                          <a class="be-img-block">
                            <div class="photo photo-type-line">
                              <a class="photo-hover" href="<%= gallery_path(gall.id) %>">
                                <div class="photo-info">
                                  <div class="headline"><%= gall.gallery_title %></div>
                                  <div class="line"></div>
                                  <div class="desc"><%= gall.gallery_description %></div>
                                </div>
                                <div class="mask"></div>
                              </a>
                              <div class="image">
                                <a class="be-img-block profile-img img-thumbnail">
                                  <img src="<%= gall.gallery_picture[0].url %>" alt="omg">
                                </a>
                              </div>
                              <div class="mask"></div>
                            </div>
                          </a>
                          <div class="headline"><a href="<%= gallery_path(gall.id) %>"><%= gall.gallery_title %></a></div>
                          <div class="desc"><%= gall.gallery_description %></div>
                          <div class="desc">Rating: <%= map[gall].to_s %></div>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% else %>
              <p>No galleries available with an average rating of 3 or higher.</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="<%= asset_path "homepage_logic.js" %>"></script>

app/views/layout/_javascripts.html.erb
<script src="<%= asset_path 'jquery.min.js' %>"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<%= asset_path 'bootstrap.min.js' %>"></script>
<!-- Theme JavaScript -->
<script src="<%= asset_path 'grayscale.js' %>"></script>
<script src="<%= asset_path 'bootstrap.min.js' %>"></script>
<!-- Plugin JavaScript -->
<script src="<%= asset_path 'jquery.easing.min.js' %>"></script>
<script src="<%= asset_path 'scrollreveal.min.js' %>"></script>
<!-- Custom scripts for this template -->
<script src="<%= asset_path 'creative.min.js' %>"></script>

app/views/layout/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="/" style="padding: 5px;">
        <img src="<%= asset_path 'logo.png' %>" style="filter: brightness(0) invert(1);">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>

        <% if session[:current_user_key] && session[:is_admin] == true %>
            <li>
              <a class="page-scroll" href="/add_profession/" rel="stylesheet">Add Profession</a>
            </li>
        <% end %>
        <li>
          <a class="page-scroll" href="/show_profile/" rel="stylesheet">My Profile</a>
        </li>
        <li>
          <a class="page-scroll" href="/search_engine/show">Search</a>
        </li>
        <% if session[:current_user_key] %>
          <li>
            <a class="page-scroll" href="/logout/">Logout</a>
          </li>
        <% else %>
          <li>
            <a class="page-scroll" href="/login_info/new" id="signUpButtonID">Sign Up</a>
          </li>
          <li>
            <a class="page-scroll" href="/login_info/login" id="loginLogoutButtonID">Login</a>
          </li>
        <% end %>
        <!--<li>-->
        <!--<a class="page-scroll" href="#postJob">Post Job</a>-->
        <!--</li>-->
        <!--<li>-->
        <!--<a class="page-scroll" href="#contact">Contact</a>-->
        <!--<a class="page-scroll" href="#postJob">Post Job</a>-->
        <!--</li>-->
        <!--<li>-->
        <!--<a class="page-scroll" href="#contact">Contact</a>-->
        <!--</li>-->
      </ul>
    </div>

    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layout/_profile_header.html.erb
<!--/ LAYOUT HEADER FILE
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%# <link rel="shortcut icon" href=""> %>

    <title href="/">FashionNXT - Your one stop shop for fashion</title>

    <!-- Bootstrap core CSS -->
    <link href="<%= asset_path 'bootstrap.css' %>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<%= asset_path 'profile.css' %>" rel="stylesheet">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family="acumin-pro","Acumin Pro","Helvetica Neue",Helvetica,Arial,sans-serif:400,300,700' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="<%= asset_path 'magnific-popup.css' %>" rel="stylesheet">
    <link href="<%= asset_path 'navbar.css.erb' %>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!--<link href="../../assets/stylesheets/creative.min.css" rel="stylesheet">-->

    <script src="<%= asset_path 'jquery.min.js' %>"></script>
    <script src="<%= asset_path 'smoothscroll.js' %>"></script>
    <script src="<%= asset_path 'Chart.js' %>"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

app/views/layout/_profile_javascripts.html.erb
<script src="<%= asset_path 'jquery.min.js' %>"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<%= asset_path 'bootstrap.min.js' %>"></script>

<!-- Plugin JavaScript -->
<!--<script src="<%= asset_path 'scrollreveal.min.js' %>"></script>-->
<script src="<%= asset_path 'jquery.easing.min.js' %>"></script>
<script src="<%= asset_path 'grayscale.js' %>"></script>

<!-- Theme JavaScript -->
<!--<script src="<%= asset_path 'popper.min.js' %>"></script>-->
<!--<script src="<%= asset_path 'creative.min.js' %>"></script>-->

<script src="<%= asset_path 'bootstrap.js' %>"></script>