config/routes.rb
  # NXTFolio : Added in Spring 2023 for tagging feature
  post '/galleries/:id/create_tagging', to: 'galleries#create_tagging', as: 'create_tagging_gallery'
  delete '/galleries/:id/destroy_tagging', to: 'galleries#destroy_tagging', as: 'destroy_tagging_gallery'

  # spring2023 add/delete images in gallery
  get '/galleries/:id/edit', to: 'galleries#edit', as: 'edit_gallery'
  get '/galleries/:id/show', to: 'galleries#show', as: 'gallery'

  put '/galleries/:id/show', to: 'galleries#update', as: 'gallery/update'


  get '/galleries/:id/delete/:idx', to: 'galleries#delete', as: 'gallery_delete'

  get '/galleries/:id/add_images', to: 'galleries#transfer', as: 'gallery_added_image'

  # Fall 2023: To add comments
  get '/galleries/:id/comments', to: 'galleries#add_comment', as: 'gallery_add_comment'
  post '/galleries/:id/comments', to: 'galleries#post_comment', as: 'gallery_post_comment'

  # Winter 2024: To add tags
  get '/galleries/:id/tags', to: 'galleries#add_tag', as: 'gallery_add_tag'
  post '/galleries/:id/tags', to: 'galleries#create_tag', as: 'gallery_create_tag'

  #get 'template/create'
  #post 'template/create' => 'template#create', :as => 'template/create1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                   registrations: "users/registrations",
                                   sessions: "devise/sessions" }, 
                    skip: [:registrations] 
  get 'general_info_list' => 'general_info#list', :as => 'general_info_list'
  get 'general_info_save' => 'general_info#save', :as => 'general_info_save'
  get 'general_info/edit' => 'general_info#edit', :as => 'general_info/edit'
  get 'general_info/edit2' => 'general_info#edit2', :as => 'general_info/edit2'
  get 'general_info/edit_travel' => 'general_info#edit_travel', :as => 'general_info/edit_travel'
  get 'general_info/new', to: 'general_info#new', as: 'general_info_new'
  get 'general_info/new2' => 'general_info#new2', :as => 'general_info/new2'
  post 'general_info/update' => 'general_info#update', :as => 'general_info/update'
  get 'general_info/edit_profession' => 'general_info#edit_profession', :as => 'general_info/edit_profession'
  post 'general_info/update_profession' => 'general_info#update_profession', :as => 'general_info/update_profession'
  get 'general_info/profession_specific' => 'general_info#profession_specific', :as => 'general_info/profession_specific'
  post 'general_info/profession_specific' => 'general_info#profession_specific_create', :as => 'general_info/profession_specific_create'
  # Follow Feature
  get 'general_info/follow/:id' => 'general_info#follow'
  get 'general_info/unfollow/:id' => 'general_info#unfollow'

  namespace :admin do
    get '/' => 'admin#landing'
    get '/create' => 'admin#create'
    post '/create' => 'admin#create'
    get '/edit' => 'admin#edit'
    post '/edit' => 'admin#edit'  
    get '/delete' => 'admin#delete'
    post '/delete' => 'admin#delete'
  end

  namespace :api do
    get 'users', to: 'general_info#index'
    get 'delete/:id', to: 'general_info#delete'
    get 'toggle_access/:id', to: 'general_info#toggle_access'
    # resources :general_info, only: [:index]
  end

  get '/general_info/make_admin/:user' => 'general_info#make_admin'

  get 'edit_job' => 'edit_job#edit'
  post 'edit_job' => 'edit_job#update'
  patch 'edit_job/update' => 'edit_job#update'
  post 'edit_job/update' => 'edit_job#update'
  get 'login_info_list' => 'login_info#list', :as => 'login_info_list'
  get 'login_info/login' => 'login_info#login', :as => 'login_info/login'
  post 'login_info/login_submit' => 'login_info#login_submit', :as => 'login_info/login_submit'
  get 'login_info/logout' => 'login_info#logout', :as => 'login_info/logout'
  post 'login_info/new' => 'login_info#new', :as => 'login_info/new'
  post 'login_info/create' => 'login_info#create', :as => 'login_info/create'
  get 'login_info/edit' => 'login_info#edit', :as => 'login_info/edit'
  post 'login_info/update' => 'login_info#update', :as => 'login_info/update'
  get 'unconfirmed_user/new' => 'unconfirmed_user#new', :as => 'unconfirmed_user/new'
  post 'unconfirmed_user/verify' => 'unconfirmed_user#verify', :as => 'unconfirmed_user/verify'
  get 'unconfirmed_user/regenerate_token' => 'unconfirmed_user#regenerate_token', :as => 'unconfirmed_user/regenerate_token'


  get 'login' => 'login_info#login', :as => 'login'
  get  'logout' => 'login_info#logout', :as => 'logout'
  # post 'create' => 'login_info#create', :as => 'create'


  get 'specific_designer_list' => 'specific_designer#list', :as => 'specific_designer_list'
  get 'specific_designer/edit' => 'specific_designer#edit', :as => 'specific_designer/edit'
  post 'specific_designer/update' => 'specific_designer#update', :as => 'specific_designer/update'
  delete 'specific_designer/destroy' => 'specific_designer#destroy', :as => 'specific_designer/destroy'

  get 'specific_model_list' => 'specific_model#list', :as => 'specific_model_list'
  get 'specific_model/edit' => 'specific_model#edit', :as => 'specific_model/edit'
  post 'specific_model/update' => 'specific_model#update', :as => 'specific_model/update'
  delete 'specific_model/destroy' => 'specific_model#destroy', :as => 'specific_model/destroy'

  get 'specific_photographer_list' => 'specific_photographer#list', :as => 'specific_photographer_list'
  get 'specific_photographer/edit' => 'specific_photographer#edit', :as => 'specific_photographer/edit'
  post 'specific_photographer/update' => 'specific_photographer#update', :as => 'specific_photographer/update'
  delete 'specific_photographer/destroy' => 'specific_photographer#destroy', :as => 'specific_photographer/destroy'

  get 'show_profile/mymodel' => 'show_profile#show_model', :as => 'show_profile_show_model'
  get 'show_profile' => 'show_profile#show_profile', :as => 'show_profile_show_profile'

  get 'search_profile/show' => 'search_profile#show', :as => 'search_profile/show'
  get 'search_profile/search' => 'search_profile#search', :as => 'search_profile/search'
  get 'search_profile/search_general' => 'search_profile#search_general', :as => 'search_profile/search_general'
  get 'search_profile/search_job' => 'search_profile#search_job', :as => 'search_profile/search_job'

  get 'search_profile/search_login' => 'search_profile#search_login', :as => 'search_profile/search_login'

  get 'search_profile/search_model' => 'search_profile#search_model', :as => 'search_profile/search_model'
  get 'search_profile/search_photographer' => 'search_profile#search_photographer', :as => 'search_profile/search_photographer'
  get 'search_profile/search_specific' => 'search_profile#search_specific', :as => 'search_profile/search_specific'
  get 'search_profile/search_specific_model' => 'search_profile#search_specific_model', :as => 'search_profile/search_specific_model'
  get 'search_profile/search_specific_photographer' => 'search_profile#search_specific_photographer', :as => 'search_profile/search_specific_photographer'
  get 'search_profile/show_profile/:id' => 'search_profile#show_profile', :as => 'search_profile/show_profile'
  get 'add_profession' => 'template#index', :as => 'template'
  post '/' => 'general_info#index', :as => 'general_info_index_post'

  get 'application/index' => 'application#index', :as => 'application/index'

  get 'search_engine/show' => 'search_engine#show', :as => 'search_engine/show'
  get 'search_engine/search' => 'search_engine#search', :as => 'search_engine/search'

  get 'job_search/jobshow' => 'job_search#jobshow', :as => 'job_search/jobshow'
  #get 'job_search/jobsearch' => 'job_search#jobsearch', :as => 'job_search/jobsearch'

  # get 'job_info/post_job' => 'job_info#post_job', :as => 'job_info/post_job1'
  post '/job_info/post_job', to: 'job_info#post_job', as: 'job_info_post_job'
  get 'job_info/index',   to: 'job_info#index',  as: 'job_info/index'
  get 'job_info/search', to: 'job_info#search', as: 'job_info/search'
  get 'job_info/new_job', to: 'job_info#new_job', as: 'job_info_new_job'
  get 'job_info/show/:id', to: 'job_info#show', as: 'job_info_show'
  # delete 'job_info/:id/del(.:format)', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/del', to: 'job_info#destroy', as: 'del_job_info'
  get '/job_info/:id/visitor', to: 'job_info#visitor_show', as: 'visitor_job_info'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Defines the root path route ("/")
  # root "articles#index"
  get 'chat', to: 'chat#index'
  post 'chat', to: 'chat#chat'

  resources :general_info
  resources :login_info
  resources :specific_designer
  resources :specific_model
  resources :specific_photographer
  resources :search_profile
  resources :template

  # for job function
  resources :job_info

#halting this changes, later will check

resources :galleries do
  resources :images, only: [:create, :destroy]
end

  resources :galleries, except: :destroy do
    resources :reviews

    # NXTFolio : Added in Spring 2023 for tagging feature
    resources :gallery_taggings, only: [:create, :destroy]

  end

  resources :search_engine
  resources :job_search


  devise_scope :user do
    get 'sign_up', to: 'login_info#new', as: :new_user_registration
    post 'sign_up', to: 'login_info#create', as: :user_registration
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'application#index'

 

end

#end

app/controllers/job_search_controller.rb
class JobSearchController < ApplicationController

    def jobshow
        @searchQuery = params[:Initkey]
        if session[:current_user_key]
            current_user = GeneralInfo.find_by(userKey: session[:current_user_key])
            @username = current_user[:first_name]
        end
    end

    # def jobsearch
    #     if session[:current_user_key]
    #         current_user = GeneralInfo.find_by(userKey: session[:current_user_key])
    #         @username = current_user[:first_name]
    #     end

    #     @params_args = params #parameters passed from view
    #     country = "United States" # change country to industry later (need to modify filterBy as well)
    #     state = @params_args[:State]
    #     city= @params_args[:City]


    #     @stateInfo=state
    #     profession = @params_args[:Profession]
    #     @filtered_users = GeneralInfo.filterBy state, profession, city

    #     #puts "Filtered users are: "
    #     #@filtered_users.each do |room|
    #     #    puts room[:first_name]
    #     #end

    #     # Search Users' general info and profession detail for the keyword
    #     @keyword = @params_args[:Keyword]
    #     @EnteredKw=@keyword
    #     @keyword= @keyword.downcase
    #     @keywordArr=@keyword.split(" ")
    #     @final_users = []
    #     if @keyword.present?
    #         @filtered_users.each do |user|
    #             if user[:job_name] == "Designer"
    #                 specific_user = SpecificDesigner.find_by(user_key: user[:userKey])
    #             elsif user[:job_name] == "Model"
    #                 specific_user = SpecificModel.find_by(user_key: user[:userKey])
    #             else
    #                 specific_user = SpecificPhotographer.find_by(user_key: user[:userKey])
    #             end
    #             user_data = specific_user.inspect.downcase.gsub(/[^a-z0-9\s]/i, '')

    #             user_data << user.inspect.downcase.gsub(/[^a-z0-9\s]/i, '')

    #             userdataString=user_data.split(" ")

    #             #previous check --user_data.include? @keyword
    #             if (userdataString & @keywordArr).any?
    #                 logger.info("Tanvir Checking")
    #                 logger.debug(user_data.inspect)
    #                 @final_users << user
    #             end
    #         end
    #     else
    #         @final_users = @filtered_users
    #     end

    #     puts "Final users are: "
    #     @final_users.each do |final|
    #         puts final
    #     end

    # end
end

app/views/job_search/jobshow.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>FashioNXT</title>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <link rel="shortcut icon" href="<%= asset_path "favicon.jpg"%>">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="<%= asset_path "adv_search.css"%>">
      <link rel="stylesheet" href="<%= asset_path "bootstrap.min.css"%>">
      <link rel="stylesheet" href="<%= asset_path "icon.css"%>">
      <link rel="stylesheet" href="<%= asset_path "loader.css"%>">
      <link rel="stylesheet" href="<%= asset_path "idangerous.swiper.css"%>">
      <link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
      <link rel="stylesheet" href="<%= asset_path "stylesheet.css"%>">
      <link rel="stylesheet" href="<%= asset_path "dropdown.css"%>">
      <link rel="stylesheet" href="<%= asset_path "search_button.css"%>">
      <link rel="stylesheet" href="<%= asset_path "jquery-ui.css"%>">
      <link rel="stylesheet" href="<%= asset_path "profile.css"%>">
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
      <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="<%= asset_path "notifications.css"%>">
      <style>
        @media (max-width: 560px) {
  .navbar-toggle {
    width: 20%; /* Take half the width */
  }

  .navbar-brand {
    width: 60%; /* Take half the width */
  }

  .navbar-brand img {
    max-width: 100%; /* Ensure the logo scales properly */
  }
}
      </style>
    </head>
    <body>
    <!-- THE HEADER -->
	<header>
		<nav class="navbar" style="color: black;">
			<div class="container-fluid">
				<div class="navbar-header">
				<button type="button" class="navbar-toggle col-6" data-toggle="collapse" data-target="#myNavbar"> 
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand col-6" href="/">
					<img class="logo-c active be_logo"  src="<%= asset_path "new_logo.png"%>" alt="logo">
				</a>
				</div>
				<!-- Main Buttons -->
				<div class="collapse navbar-collapse" id="myNavbar">
        <% if session[:current_user_key] %>
				<ul class="nav navbar-nav">
          <li><a href="/job_info">Manage Job</a></li>
          <li><a href="/job_info/new_job">Post Job</a></li>
					<li><a href="/general_info/edit_travel">Travel</a></li>
          <% if @on_Own %>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Edit Profile
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><a href="/general_info/edit">Edit Personal Info</a></li>
							<% if @attribute_titles && !@is_Admin %>
								<li><a href="/general_info/edit2">Edit Professional Info</a></li>
							<% end %>
								<li><a href="/login_info/edit">Change Password</a></li>
							<% if !@is_Admin %>
								<li><a href="general_info/make_admin/<%=@addUser%>">Make Administrator</a></li>
							<% elsif @is_Admin%>
								<li><a href="/admin">Admin Dashboard</a></li>
							<% end %>
						</ul>
					</li>
          <% end %>
					<li class="active"><a href="/show_profile">My Profile</a></li>
					<li><a href="/search_engine/show">Search</a></li>
					<li><a href="/chat">AI Chatbot</a></li>
          <% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
				<% if session[:current_user_key] %>
					<!-- Notifications Dropdown -->
					<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" id="notificationsDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
						<% if @user && @user.notification %>
						<i class="fa-regular fa-bell fa-xl" style="color:#147efb"></i>
						<% else %>
						<i class="fa-regular fa-bell fa-xl" style="color:black"></i>
						<% end %>
					</a>
					<ul class="dropdown-menu" aria-labelledby="notificationsDropdown">
						<% if @user && @user.notification %>
						<% @notifications_from.each do |notification| %>
							<li><a class="dropdown-item" href="/dm/<%= notification %>">
							<b><%= GeneralInfo.find_by(id: notification).first_name %> <%= GeneralInfo.find_by(id: notification).last_name %> sent you a message!</b>
							</a></li>
						<% end %>
						<% else %>
						<li class="dropdown-item text-center">
							<i class="fa-regular fa-circle-check fa-5x" style="color:black; padding:30px;"></i>
							<div style="color: black; height: 20px;"><b>You're all caught up!</b></div>
							<div style="color: black; height: 20px;"><b>No new messages.</b></div>
						</li>
						<% end %>
					</ul>
					</li>

					<!-- Direct Messages Button -->
					<li class="nav-item">
					<a href="/dm" class="nav-link" id="dm">
						<i class="fa-regular fa-message fa-xl" style="color:black"></i>
					</a>
					</li>

					<!-- Log Out Button -->
					<li class="nav-item">
					<%= link_to logout_path, method: :get, class: "nav-link" do %>
						<span class="glyphicon glyphicon-log-out"></span> Log out
					<% end %>
					</li>
				<% else %>
					<!-- Log In Button -->
					<li class="nav-item">
					<%= link_to login_path, method: :get, class: "nav-link" do %>
						<span class="glyphicon glyphicon-log-in"></span> Sign In
					<% end %>
          <!-- Sign Up Button -->
					<li class="nav-item">
					<%= link_to new_user_registration_path, method: :get, class: "nav-link" do %>
						<span class="fa fa-user-plus"></span> Sign Up
					<% end %>
					</li>
				<% end %>
				</ul>

				</div>
			</div>
		</nav>
	</header>
      <!-- CONTENT -->

      
	
    


      <div class="s008" id='head-bg-img'>


      


        <%= form_tag(job_info_search_path, :method=>'get') do %>
        <div class="searchContainer" id="advsearch">
          <h5 class="mod-1">What jobs are you looking for?</h5>
          <div class="col-md-1">
          </div>
          <div class="col-md-12" >
            <div id="custom-search-input">
              <div class="input-group col-md-12">
                <input name="Keyword" id="search" type="text" class="form-control input-lg" value="<%= @searchQuery %>" />
                <span class="input-group-btn">
                          <button id="show_page_button" class="btn btn-info btn-lg" type="submit">
                              <i class="glyphicon glyphicon-search"></i>
                          </button>
                      </span>
              </div>
            </div>

            <div class="buttongroup-class">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group"> <label class="changedLabel">Category</label> <select id='general_info_industry' name="Industry" data-trigger="" class="form-control select2 select2-hidden-accessible" style="width: 90%;" tabindex="-1" aria-hidden="true">
                    <option placeholder="" value="">Select</option>
                    <option>Creators</option>
                    <option>Services</option>
                    <option>Makers</option>
                  </select> </div> <!-- /.form-group -->
                </div> <!-- /.col -->

                <div class="col-md-6">
                  <div class="form-group"> <label class="changedLabel">Profession</label> <select id="general_info_job_name" name="Profession" data-trigger="" class="form-control select2 select2-hidden-accessible" style="width: 90%;" tabindex="-1" aria-hidden="true">
                    <option placeholder="" value="">Select</option>
                    <option>Brand Owner</option>
                    <option>Designer</option>
                    <option>Other Creator</option>
                    <option>Model</option>
                    <option>Photographer</option>
                    <option>Sales</option>
                    <option>Marketing</option>
                    <option>Retail</option>
                    <option>Visual</option>
                    <option>Content Creator</option>
                    <option>Blogger</option>
                    <option>Influencer</option>
                    <option>Forecasting</option>
                    <option>Finances</option>
                    <option>Other Service</option>
                    <option>Manufacturing</option>
                    <option>Materials</option>
                    <option>Other Makers</option>
                  </select> </div> <!-- /.form-group -->
                </div> <!-- /.col -->


                <div class="col-md-4">
                  <div class="form-group"> <label class="changedLabel">Country</label> <select name="Country" id="country" data-trigger="" class="countries form-control select2 select2-hidden-accessible" style="width: 90%;" tabindex="-1" aria-hidden="true">
                    <option value="">Select Country</option>
                  </select> </div> <!-- /.form-group -->
                </div> <!-- /.col -->

                <div class="col-md-4">
                  <div class="form-group"> <label class="changedLabel">State</label> <select name="State" id="state" data-trigger="" class="states form-control select2 select2-hidden-accessible" style="width: 90%;" tabindex="-1" aria-hidden="true">
                    <option value="">Select State</option>
                  </select> </div> <!-- /.form-group -->
                </div> <!-- /.col -->

                <div class="col-md-4">
                  <div class="form-group"> <label class="changedLabel">City</label>
                    <input type="text" name="City" id="city" class="form-control" style="width: 90%;" tabindex="-1" aria-hidden="true">
                </div> <!-- /.col -->


              </div>


            </div>


              </div>
            </div>
        </div>
        <% end %>
      </div>



      <script>
          $(document).ready(function() {
              $('.mdb-select').materialSelect();
              $('.select-wrapper.md-form.md-outline input.select-dropdown').bind('focus blur', function () {
                  $(this).closest('.select-outline').find('label').toggleClass('active');
                  $(this).closest('.select-outline').find('.caret').toggleClass('active');
              });
          });

        </script>
      <script>
          $(function(){
              $(".dropdown-menu li a").click(function(){
                  $(this).closest('.btn-group').find(".btn:first-child").text($(this).text());
                  $(this).closest('.btn-group').find(".btn:first-child").val($(this).text());
              });
          });
      </script>
      <script>
        const customSelects = document.querySelectorAll("select");
        const deleteBtn = document.getElementById('delete')
        const choices = new Choices('select',
        {
          searchEnabled: false,
          removeItemButton: true,
          itemSelectText: '',
        });
        for (let i = 0; i < customSelects.length; i++)
        {
          customSelects[i].addEventListener('addItem', function(event)
          {
            if (event.detail.value)
            {
              let parent = this.parentNode.parentNode
              parent.classList.add('valid')
              parent.classList.remove('invalid')
            }
            else
            {
              let parent = this.parentNode.parentNode
              parent.classList.add('invalid')
              parent.classList.remove('valid')
            }
          }, false);
        }
        deleteBtn.addEventListener("click", function(e)
        {
          e.preventDefault()
          const deleteAll = document.querySelectorAll('.choices__button')
          for (let i = 0; i < deleteAll.length; i++)
          {
            deleteAll[i].click();
          }
        });

      </script>
        <script src="<%= asset_path "jquery.min.js"%>"></script>
        <script src="<%= asset_path "jquery-ui.js"%>"></script>
        <script src="<%= asset_path "bootstrap.min.js"%>"></script>
        <script src="<%= asset_path "idangerous.swiper.min.js"%>"></script>
        <script src="<%= asset_path "jquery.mixitup.js"%>"></script>
        <script src="<%= asset_path "jquery.viewportchecker.min.js"%>"></script>
        <script src="<%= asset_path "global.js"%>"></script>
        <script src="<%= asset_path "professionPicker.js"%>"></script>
        <script src="<%= asset_path "location.js"%>"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
  </html>